=== ChrisMJones1/N01352022_HTTP5203_Assignment2/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user_id" type="id"></xs:element>
                            <xs:element name="username" type="xs:string"></xs:element>
                            <xs:element name="password" type="xs:string"></xs:element>
                            <xs:element name="notes" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="user_type" type="usertype" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="usertype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="admin" />
            <xs:enumeration value="client" />
            <xs:enumeration value="support" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="id">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ChrisMJones1/N01352022_HTTP5203_Assignment2/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user user_type="admin">
        <user_id>1</user_id>
        <username>admin@support.net</username>
        <password>482c811da5d5b4bc6d497ffa98491e38</password>
        <notes>Primary Admin user account</notes>
    </user>
    <user user_type="client">
        <user_id>2</user_id>
        <username>LettuceLover@leafy.com</username>
        <password>1f87db07f7a31acf8f75fc57e27fb92b</password>
        <notes>This client really likes lettuce</notes>
    </user>
    <user user_type="support">
        <user_id>3</user_id>
        <username>Support-1@support.net</username>
        <password>c158b33d64e5bf549328f8d8c8332fac</password>
        <notes></notes>
    </user>
</users>
